import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import {Calendar,Clock3,FileText,ShieldCheck,Plane,LayoutDashboard,LogOut,Settings,Users,AlertTriangle,BookOpen,Plus,ChevronRight} from 'lucide-react';
import './styles.css';

const supabase=createClient(import.meta.env.VITE_SUPABASE_URL||'',import.meta.env.VITE_SUPABASE_ANON_KEY||'');

function App(){
 const [session,setSession]=useState(null),[profile,setProfile]=useState(null),[tab,setTab]=useState('dashboard'),[loading,setLoading]=useState(true);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)supabase.from('profiles').select('*').eq('id',session.user.id).single().then(({data})=>{setProfile(data);setLoading(false)});else setLoading(false)},[session]);
 if(loading)return <div className="center">Loading AeroPath…</div>;
 if(!session)return <Auth/>;
 return <Portal session={session} profile={profile} tab={tab} setTab={setTab}/>;
}
function Auth(){
 const [mode,setMode]=useState('signin'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[msg,setMsg]=useState('');
 async function submit(e){e.preventDefault();setMsg('');const r=mode==='signin'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password,options:{data:{full_name:name}}});if(r.error)setMsg(r.error.message);else if(mode==='signup')setMsg('Account created. Check your email if confirmation is enabled.')}
 return <div className="auth"><div className="brand">AEROPATH<span>OPS</span></div><div className="auth-card"><div className="eyebrow">FLIGHT SIMULATION OPERATIONS</div><h1>{mode==='signin'?'Welcome back':'Create your AeroPath account'}</h1><p className="muted">A lightweight operational portal for simulation teams.</p><form onSubmit={submit}>{mode==='signup'&&<input placeholder="Full name" value={name} onChange={e=>setName(e.target.value)} required/>}<input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required/><button className="primary">{mode==='signin'?'Sign in':'Create account'}</button></form>{msg&&<div className="notice">{msg}</div>}<button className="link" onClick={()=>setMode(mode==='signin'?'signup':'signin')}>{mode==='signin'?'Need an account? Create one':'Already have an account? Sign in'}</button></div></div>
}
function Portal({session,profile,tab,setTab}){
 const role=profile?.role||'STUDENT';
 const nav=role==='STUDENT'?['dashboard','bookings','progress','documents','safety']:role==='INSTRUCTOR'?['dashboard','bookings','students','progress','safety']:role==='SAFETY_MANAGER'?['dashboard','safety','reports']:['dashboard','simulators','bookings','users','modules','audit'];
 const titles={dashboard:'Virtual Cockpit',bookings:'Simulator Operations',progress:'Training Progress',documents:'Documents',safety:'Safety Control Tower',students:'Students',simulators:'Simulator Inventory',users:'User Management',modules:'System Modules',audit:'Audit Activity',reports:'Safety Reports'};
 const pages={dashboard:<Dashboard profile={profile}/>,bookings:<Bookings profile={profile}/>,progress:<Progress profile={profile}/>,documents:<Documents profile={profile}/>,safety:<Safety/>,reports:<Safety/>,simulators:<Simulators/>,modules:<Modules/>,audit:<Audit/>,students:<Students/>};
 return <div className="app"><aside><div className="logo">AEROPATH<span>OPS</span></div><div className="role">{role.replace('_',' ')}</div>{nav.map(n=><button key={n} className={tab===n?'nav active':'nav'} onClick={()=>setTab(n)}>{icon(n)}<span>{titles[n]}</span></button>)}<div className="side-bottom"><button className="nav" onClick={()=>supabase.auth.signOut()}><LogOut/><span>Sign out</span></button></div></aside><main><header><div><div className="eyebrow">AEROPATH OPERATIONS</div><h2>{titles[tab]}</h2></div><div className="user">{profile?.full_name||session.user.email}</div></header><section className="content">{pages[tab]||<Empty title={titles[tab]}/>}</section></main></div>
}
function icon(n){const C={dashboard:LayoutDashboard,bookings:Calendar,progress:BookOpen,documents:FileText,safety:ShieldCheck,students:Users,simulators:Plane,users:Users,modules:Settings,audit:Clock3,reports:AlertTriangle}[n]||ChevronRight;return <C size={18}/>}
function Dashboard({profile}){return <><div className="hero"><div><div className="eyebrow">OPERATIONAL STATUS</div><h1>Good to see you, {profile?.full_name?.split(' ')[0]||'pilot'}.</h1><p>Everything you need for the next simulator session, in one cockpit.</p></div><Plane size={72}/></div><div className="grid four"><Card icon={<Clock3/>} label="Total simulator hours" value={`${Number(profile?.total_sim_hours||0).toFixed(1)} h`}/><Card icon={<Calendar/>} label="Next session" value="No session booked"/><Card icon={<FileText/>} label="Preparation" value="Not started"/><Card icon={<ShieldCheck/>} label="Safety notices" value="2 active"/></div><div className="grid two"><Panel title="Simulator fleet"><Fleet/></Panel><Panel title="Quick actions"><div className="actions"><Action t="Book simulator"/><Action t="Open pre-flight preparation"/><Action t="View documents"/><Action t="View progress"/></div></Panel></div></>}
function Card({icon,label,value}){return <div className="card"><div className="cardicon">{icon}</div><div className="muted">{label}</div><strong>{value}</strong></div>}
function Panel({title,children}){return <div className="panel"><div className="panel-title"><h3>{title}</h3><span>›</span></div>{children}</div>}
function Action({t}){return <button className="action">{t}<ChevronRight size={17}/></button>}
function Fleet(){const [data,setData]=useState([]);useEffect(()=>{supabase.from('simulators').select('*').order('name').then(({data})=>setData(data||[]))},[]);return <div className="fleet">{data.map(s=><div className="row" key={s.id}><Plane size={20}/><div><b>{s.name}</b><small>{s.simulator_type}</small></div><span className={'status '+s.status.toLowerCase()}>{s.status}</span></div>)}</div>}
function Bookings({profile}){const [data,setData]=useState([]),[sims,setSims]=useState([]),[open,setOpen]=useState(false),[form,setForm]=useState({simulator_id:'',starts_at:'',ends_at:'',notes:''});
 async function load(){let q=supabase.from('bookings').select('*,simulators(name,simulator_type)').order('starts_at');if(profile?.role==='STUDENT')q=q.eq('student_id',profile.id);const r=await q;setData(r.data||[]);const s=await supabase.from('simulators').select('*').eq('status','AVAILABLE');setSims(s.data||[])}
 useEffect(()=>{load()},[profile]);
 async function create(e){e.preventDefault();const r=await supabase.from('bookings').insert({...form,student_id:profile.id,status:'REQUESTED'});if(r.error)alert(r.error.message);else{setOpen(false);load()}}
 return <><div className="toolbar"><div><div className="muted">Simulator sessions</div><h3>Bookings</h3></div>{profile?.role==='STUDENT'&&<button className="primary small" onClick={()=>setOpen(!open)}><Plus size={16}/> Request booking</button>}</div>{open&&<form className="panel formgrid" onSubmit={create}><select value={form.simulator_id} onChange={e=>setForm({...form,simulator_id:e.target.value})} required><option value="">Select simulator</option>{sims.map(s=><option key={s.id} value={s.id}>{s.name} — {s.simulator_type}</option>)}</select><input type="datetime-local" value={form.starts_at} onChange={e=>setForm({...form,starts_at:e.target.value})} required/><input type="datetime-local" value={form.ends_at} onChange={e=>setForm({...form,ends_at:e.target.value})} required/><input placeholder="Notes (optional)" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><button className="primary">Submit request</button></form>}<div className="panel"><table><thead><tr><th>Simulator</th><th>Start</th><th>End</th><th>Status</th></tr></thead><tbody>{data.map(b=><tr key={b.id}><td>{b.simulators?.name}</td><td>{new Date(b.starts_at).toLocaleString()}</td><td>{new Date(b.ends_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</td><td><span className="pill">{b.status}</span></td></tr>)}</tbody></table>{!data.length&&<Empty title="No bookings yet" text="Request your first simulator session to get started."/>}</div></>
}
function Progress({profile}){const [rows,setRows]=useState([]);useEffect(()=>{if(profile)supabase.from('student_progress').select('*,lessons(name,courses(name))').eq('student_id',profile.id).then(({data})=>setRows(data||[]))},[profile]);return <div className="panel"><h3>Training progress</h3><p className="muted">Lesson and course progress recorded for your account.</p>{rows.map(r=><div className="row" key={r.id}><BookOpen size={20}/><div><b>{r.lessons?.name}</b><small>{r.lessons?.courses?.name}</small></div><span className="pill">{r.status}</span></div>)}{!rows.length&&<Empty title="No progress recorded yet"/>}</div>}
function Documents({profile}){const [rows,setRows]=useState([]);useEffect(()=>{if(profile)supabase.from('documents').select('*').eq('owner_id',profile.id).order('created_at',{ascending:false}).then(({data})=>setRows(data||[]))},[profile]);return <div className="panel"><h3>Your documents</h3><p className="muted">Document management is connected to the database; advanced upload UI is a later module.</p>{rows.map(d=><div className="row" key={d.id}><FileText/><div><b>{d.title}</b><small>{d.category||'Document'}</small></div></div>)}{!rows.length&&<Empty title="No documents yet"/>}</div>}
function Safety(){const [rows,setRows]=useState([]);useEffect(()=>{supabase.from('safety_notices').select('*').eq('published',true).order('created_at',{ascending:false}).then(({data})=>setRows(data||[]))},[]);return <div className="grid two">{rows.map(n=><div className="notice-card" key={n.id}><div className="eyebrow">{n.severity}</div><h3>{n.title}</h3><p>{n.body}</p><small>{new Date(n.created_at).toLocaleDateString()}</small></div>)}{!rows.length&&<Empty title="No active safety notices"/>}</div>}
function Simulators(){return <div className="panel"><h3>Simulator inventory</h3><Fleet/></div>}
function Modules(){const [rows,setRows]=useState([]);useEffect(()=>{supabase.from('system_modules').select('*').order('name').then(({data})=>setRows(data||[]))},[]);return <div className="panel"><h3>System modules</h3>{rows.map(m=><div className="row" key={m.key}><Settings/><div><b>{m.name}</b><small>{m.key}</small></div><span className={'status '+(m.enabled?'available':'inactive')}>{m.enabled?'ENABLED':'DISABLED'}</span></div>)}</div>}
function Audit(){const [rows,setRows]=useState([]);useEffect(()=>{supabase.from('audit_logs').select('*').order('created_at',{ascending:false}).limit(50).then(({data})=>setRows(data||[]))},[]);return <div className="panel"><h3>Recent audit activity</h3>{rows.map(r=><div className="row" key={r.id}><Clock3/><div><b>{r.action}</b><small>{r.entity_type||'system'} · {new Date(r.created_at).toLocaleString()}</small></div></div>)}{!rows.length&&<Empty title="No audit activity yet"/>}</div>}
function Students(){const [rows,setRows]=useState([]);useEffect(()=>{supabase.from('profiles').select('*').eq('role','STUDENT').order('full_name').then(({data})=>setRows(data||[]))},[]);return <div className="panel"><h3>Students</h3>{rows.map(s=><div className="row" key={s.id}><Users/><div><b>{s.full_name||'Unnamed student'}</b><small>{s.email}</small></div><span className="pill">{Number(s.total_sim_hours||0).toFixed(1)} h</span></div>)}</div>}
function Empty({title,text}){return <div className="empty"><div className="cardicon"><FileText/></div><h3>{title}</h3><p className="muted">{text||'Nothing to display yet.'}</p></div>}
createRoot(document.getElementById('root')).render(<App/>);